resources:
- resources/dashboard-service.yaml
- resources/default-cert-secret.yaml
- resources/deployment.yaml
- resources/prometheus-service.yaml
- resources/service.yaml
- resources/rbac.yaml

namespace: kube-system

commonLabels:
  app.kubernetes.io/name: traefik