apiVersion: v1
kind: Service
metadata:
  name: traefik-prometheus
  annotations:
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  ports:
    - port: 9100
      name: metrics
      targetPort: metrics
