apiVersion: v1
kind: Service
metadata:
  name: traefik
spec:
  type: LoadBalancer
  loadBalancerIP: 34.95.5.107
  externalTrafficPolicy: Cluster
  ports:
  - port: 443
    name: https
    targetPort: https
  - port: 80
    name: http
    targetPort: http
